version: "3.8"

services:
  frontend:
    image: sgh-frontend
    container_name: sgh-frontend
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: https://app.sgh-sistema-gestion-horarios.online/api
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: always
